In [1]:
# x_data = (예습시간, 복습시간)
# t_data = 1 (Pass), 0 (Fail)

import numpy as np

x_data = np.array([ [2, 4], [4, 11], [6, 6], [8, 5], [10, 7], [12, 16], [14, 8], [16, 3], [18, 7] ])
t_data = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1]).reshape(9, 1)

# 데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape) 

x_data.ndim =  2 , x_data.shape =  (9, 2)
t_data.ndim =  2 , t_data.shape =  (9, 1)


In [2]:
W = np.random.rand(2, 1)  # 2X1 행렬
b = np.random.rand(1)  
print("W = ", W, ", W.shape = ", W.shape, ", b = ", b, ", b.shape = ", b.shape)

W =  [[0.59037318]
 [0.97928723]] , W.shape =  (2, 1) , b =  [0.02729022] , b.shape =  (1,)


In [3]:
# classification 이므로 출력함수로 sigmoid 정의

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [4]:
# 최종출력은 y = sigmoid(Wx+b) 이며, 손실함수는 cross-entropy 로 나타냄

def loss_func(x, t):
    
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )  

In [5]:
def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

In [6]:
def error_val(x, t):
    delta = 1e-7    # log 무한대 발산 방지
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    # cross-entropy 
    return  -np.sum( t*np.log(y + delta) + (1-t)*np.log((1 - y)+delta ) )  

def predict(x):
    
    z = np.dot(x,W) + b
    y = sigmoid(z)
    
    if y > 0.5:
        result = 1  # True
    else:
        result = 0  # False
    
    return y, result

In [7]:
learning_rate = 1e-2  # 1e-2, 1e-3 은 손실함수 값 발산

f = lambda x : loss_func(x_data,t_data)

print("Initial error value = ", error_val(x_data, t_data), "Initial W = ", W, "\n", ", b = ", b )

for step in  range(80001):  
    
    W -= learning_rate * numerical_derivative(f, W)
    
    b -= learning_rate * numerical_derivative(f, b)
    
    if (step % 400 == 0):
        print("step = ", step, "error value = ", error_val(x_data, t_data), "W = ", W, ", b = ",b )

Initial error value =  37.33068348759425 Initial W =  [[0.59037318]
 [0.97928723]] 
 , b =  [0.02729022]
step =  0 error value =  26.68331254985706 W =  [[0.392678  ]
 [0.72511978]] , b =  [-0.01242824]
step =  400 error value =  2.140219638017979 W =  [[ 0.43790826]
 [-0.07630044]] , b =  [-2.88760527]
step =  800 error value =  1.5379797403708106 W =  [[ 0.54895556]
 [-0.02084587]] , b =  [-4.42944449]
step =  1200 error value =  1.2509555800341814 W =  [[0.63339668]
 [0.01273233]] , b =  [-5.49741818]
step =  1600 error value =  1.0795956860668237 W =  [[0.70202716]
 [0.03707916]] , b =  [-6.32336554]
step =  2000 error value =  0.963523629329504 W =  [[0.76012571]
 [0.05668202]] , b =  [-7.00331284]
step =  2400 error value =  0.8783247469050239 W =  [[0.81064909]
 [0.07358101]] , b =  [-7.58588734]
step =  2800 error value =  0.8122385444926399 W =  [[0.8554231 ]
 [0.08884687]] , b =  [-8.09896478]
step =  3200 error value =  0.7588882365797798 W =  [[0.89565838]
 [0.10309531]] , 

step =  31600 error value =  0.1698360114178903 W =  [[1.78491036]
 [0.70500752]] , b =  [-20.2135295]
step =  32000 error value =  0.16801708027831802 W =  [[1.79122373]
 [0.7097176 ]] , b =  [-20.29852611]
step =  32400 error value =  0.16623618069151527 W =  [[1.79747311]
 [0.71437446]] , b =  [-20.38262887]
step =  32800 error value =  0.16449214173444474 W =  [[1.80365979]
 [0.71897927]] , b =  [-20.46585617]
step =  33200 error value =  0.16278383985991787 W =  [[1.80978498]
 [0.72353317]] , b =  [-20.54822583]
step =  33600 error value =  0.16111019652677047 W =  [[1.81584987]
 [0.72803726]] , b =  [-20.62975511]
step =  34000 error value =  0.1594701759711286 W =  [[1.82185563]
 [0.73249258]] , b =  [-20.71046079]
step =  34400 error value =  0.15786278310913276 W =  [[1.82780339]
 [0.73690017]] , b =  [-20.79035915]
step =  34800 error value =  0.1562870615621276 W =  [[1.83369423]
 [0.74126102]] , b =  [-20.86946597]
step =  35200 error value =  0.15474209179590434 W =  [[1.8

step =  63600 error value =  0.09068572180373159 W =  [[2.15476219]
 [0.97333213]] , b =  [-25.14797977]
step =  64000 error value =  0.09015775949789741 W =  [[2.15821886]
 [0.97578212]] , b =  [-25.19375815]
step =  64400 error value =  0.08963586524840886 W =  [[2.16165596]
 [0.97821741]] , b =  [-25.23927259]
step =  64800 error value =  0.08911993557886899 W =  [[2.16507372]
 [0.98063819]] , b =  [-25.2845261]
step =  65200 error value =  0.08860986934313556 W =  [[2.16847235]
 [0.98304462]] , b =  [-25.32952162]
step =  65600 error value =  0.0881055676602401 W =  [[2.17185206]
 [0.98543687]] , b =  [-25.37426207]
step =  66000 error value =  0.08760693385155759 W =  [[2.17521305]
 [0.9878151 ]] , b =  [-25.4187503]
step =  66400 error value =  0.08711387338002789 W =  [[2.17855553]
 [0.99017949]] , b =  [-25.46298911]
step =  66800 error value =  0.08662629379132898 W =  [[2.1818797 ]
 [0.99253018]] , b =  [-25.50698126]
step =  67200 error value =  0.08614410465702373 W =  [[2.

In [8]:
test_data = np.array([3, 17]) # (예습, 복습) = (3, 17) => Fail (0)
predict(test_data) 

(array([0.12873302]), 0)

In [9]:
test_data = np.array([5, 8]) # (예습, 복습) = (5, 8) => Fail (0)

predict(test_data) 

(array([0.00098961]), 0)

In [11]:
test_data = np.array([7, 21]) # (예습, 복습) = (7, 21) => Pass (1)

predict(test_data) 

(array([0.99998957]), 1)

In [12]:
test_data = np.array([12, 0])  # (예습, 복습) = (12, 0) => Pass (1)

predict(test_data) 

(array([0.63491963]), 1)